### ISSUE TITLE
Inconsistent documentation

### ISSUE THREAD

**Issue by shredEngineer** [feluxe/sty#41] opened 2022-01-11 17:10 UTC
Hi, thank you for making `sty`. I'm using Python 3.9 with sty 1.0.0rc1 and I use it extensively in my projects.

However, the documentation doesn't seem to be up to date.
[Here](https://sty.mewo.dev/docs/resetting.html) it says `rs.bold_faint` / `rs.faint_bold`,
but the actual implementation provides `rs.bold_dim` / `rs.dim_bold`.

Moreover, what is the reason for not simply calling this one `rs.bold`?
This is confusing for me at least, and I find it ugly because it is not symmetric to `ef.bold`.

Have a great evening!

**Comment by feluxe** [comment] 2022-01-15 13:55
Thanks for reporting this!

The docs are indeed out of sync. `bold_dim` is correct. I'm going to update them.

> Moreover, what is the reason for not simply calling this one rs.bold?
This is confusing for me at least, and I find it ugly because it is not symmetric to ef.bold.

This is a really good question. I think I haven't documented this anywhere yet. I'm indeed not happy with `rs.bold_dim` and `rs.dim_bold`, but there are some shortcomings within the underlying terminal systems which let me to go with those over `rs.bold` and `rs.dim`.

Since this is something I haven't made my mind up with yet, I opened this ticket https://github.com/feluxe/sty/issues/42. The problem is explained there in more detail.

**Comment by feluxe** [comment] 2022-01-25 01:22
Fixed with 8bb1cd2f159a6d844741fd21a4a98450fbe12152

**Closed by feluxe** 2022-01-25 01:22 UTC
Labels: documentation
